### ISSUE TITLE
onNewOtherMsg回调返回的消息如何解析

### ISSUE THREAD

**Issue by fengdianxun** [zhaoyang21cn/ILiveSDK_Android_Demos#12]
1、为什么我用sendCustomCmd发消息，但是消息用onNewOtherMsg回执？
我想用onNewCustomMsg接收该如何发消息？

2、TIMMessage类型的消息如何解析出我定义的cmd？

谢谢！

**Comment by guozhuoxing** [comment]
/**
     * 用户自定义消息段
     */
    public static final int ILVLIVE_CMD_CUSTOM_LOW_LIMIT = 0x800;          //自定义消息段下限
    public static final int ILVLIVE_CMD_CUSTOM_UP_LIMIT = 0x900;          //自定义消息段上线

 在这个字段内 会被当成是客户自定义消息 如果不在这个范围内 就会当成其他消息

**Comment by guozhuoxing** [comment]
2 参考我们
    private boolean parseIMMessage(TIMMessage currMsg) {
        boolean bInnerMsg = false;
        for (int j = 0; j < currMsg.getElementCount(); j++) {
            if (currMsg.getElement(j) == null)
                continue;
            TIMElem elem = currMsg.getElement(j);
            TIMElemType type = elem.getType();
            String sendId = currMsg.getSender();


//                定制消息
            if (type == TIMElemType.Custom) {
                TIMCustomElem customElem = (TIMCustomElem) elem;
                if (liveConfig.getLiveMsgListener() != null) {
                    bInnerMsg = handleCustomMsg(customElem, sendId);
                }

                continue;
            }

            //文本消息
            if (type == TIMElemType.Text) {
                TIMTextElem textElem = (TIMTextElem) elem;
                if (liveConfig.getLiveMsgListener() != null){
                    ILVText ilvText;
                    bInnerMsg = true;
                    if (TIMConversationType.C2C == currMsg.getConversation().getType()){
                        ilvText = new ILVText(ILVText.ILVTextType.eC2CMsg, currMsg.getConversation().getPeer(), textElem.getText());
                    }else if (TIMConversationType.Group == currMsg.getConversation().getType()){
                        ilvText = new ILVText(ILVText.ILVTextType.eGroupMsg, currMsg.getConversation().getPeer(), textElem.getText());
                    }else{
                        bInnerMsg = false;  // 归为other消息
                        continue;
                    }

                    ilvText.setPriority(currMsg.getPriority());
                    liveConfig.getLiveMsgListener().onNewTextMsg(ilvText, sendId);
                }
            }
        }

        return bInnerMsg;
    }
