### ISSUE TITLE
随心播兼容性

### ISSUE THREAD

**Issue by naivor** [zhaoyang21cn/ILiveSDK_Android_Demos#15]
最新的1.8.4中的so包兼容性不是很好，在4.0-4.4的手机上会出现崩溃

A/libc: Fatal signal 11 (SIGSEGV) at 0xdead0000 (code=1), thread 1832

**Comment by guozhuoxing** [comment]
建议升级到1.8.5再试下 如果还有再群里反馈给二线  提供LOG
