### ISSUE TITLE
互动直播qavsdk.jar 与 腾讯直播 txrtmp.jar 发生冲突

### ISSUE THREAD

**Issue by LCM-93** [zhaoyang21cn/ILiveSDK_Android_Demos#18]
同一个工程中同时引入腾讯直播txrtmp.jar 包与互动直播SDK时AudioDeviceInterface.class类就会发生冲突!

![image](https://cloud.githubusercontent.com/assets/16421990/23650565/81f463d2-035d-11e7-9bf2-27903308b597.png)

这个问题该咋解决??????

**Comment by xkazer** [comment]
可以引入直播精简版，或参考我们的demo，使用gradle的方式引入rtmpsdk

**Comment by RayGyoe** [comment]
下载最新版本好像解决了该问题
