### ISSUE TITLE
onNewIncomingCall 会收到很多条离线时人家发起的请求

### ISSUE THREAD

**Issue by arthur20150522** [zhaoyang21cn/ILiveSDK_Android_Demos#19]
离线用户登录后：
onNewIncomingCall回调 会收到很多条离线时人家发起的请求。
这种sdk是不是应该加个时间过滤，或者提供一个时间对比参数给开发者自行判断。。。。

**Comment by xkazer** [comment]
发起呼叫时的option可以配置setOnlineCall参数，该参数配置为true，则来电只有在线用户才能收到。
另外onNewIncomingCall里的notification是可以通过getTimeStamp方法获取来电的时间戳的

**Comment by arthur20150522** [comment]
额，我们现在是这样的，因为sdk发送128命令的时候，没有组装离线推送消息，所有我们在makecall的时候发送了自己的一个组装好的离线消息，让用户感知并打开app。
但是打开的时候，概率会多次回调onNewIncomingCall。

**Comment by arthur20150522** [comment]
另外有一个场景：
1、我对对方发起makecall
2、然后切断网络模拟网络拨动
3、关闭会话，执行ondestory()那些。

恢复网络之后会出现无法makecall的情况。

调试发现是你们的CallMgr里面，  

```
private boolean changeStatus(CallStatus newStatus) { 
// 我此时的newStatus值是CallStatus.eCallEnter
//mStatus 值是 eCallEnd
....
    case eCallEnd:
                bRet = (CallStatus.eCallIdle == newStatus);
                break;
```

你们changeStatus(CallStatus.eCallEnd);后面是不是都要必须带 changeStatus(CallStatus.eCallIdle);
不然无法发起会话。。。。。。。。

**Comment by xkazer** [comment]
这个状态异常为已知bug，请使用最新版本1.0.13验证

**Comment by arthur20150522** [comment]
好的，我试试看，谢谢，辛苦了。

**Comment by arthur20150522** [comment]
请问，最新的版本，你们是用了rxjava2吗？ 
我发现用了新版本之后，就出现rxjava版本冲突了

**Comment by JasonXiao001** [comment]
用了rxjava2 ，现在是怎么冲突的？
compile (compile 'com.tencent.livesdk:livesdk:1.1.0') {
        exclude group: 'io.reactivex',module:'rxjava'
    }
试一下？

**Comment by arthur20150522** [comment]
因为我自己用的是rxjava1哦，发现最新版一导入就出现rxjava重复的问题。
好的，我试试看。

**Comment by arthur20150522** [comment]
不知道会不会有问题哦，加入这段代码之后好的。
`add this in app/build.gradle:

``` android {

......

packagingOptions {
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/rxjava.properties'
} ```

**Comment by JasonXiao001** [comment]
是的，这样也可以去掉重复的文件
