### ISSUE TITLE
miui8 第一次获取相机权限失败

### ISSUE THREAD

**Issue by zhxacg** [zhaoyang21cn/ILiveSDK_Android_Demos#2]

**Comment by zhxacg** [comment]
1， miui8(6.0以下的机子)，第一次使用，获取不到摄像头画面和权限
2， 6.0的miui8， targetSdkVersion <23 , 也是一样的问题

**Comment by guozhuoxing** [comment]
我用小米5 测试下 miui8  删掉应用 重新安装 第一次 没有问题

**Comment by guozhuoxing** [comment]
6.0不能低于23

**Comment by tangpj** [comment]
这个问题应该是没有处理好android 6.0运行时权限的原因。只是测试的话，可以在设置中手动打开相机权限。实际应用的话可以在调用sdk前先判断下权限有没有打开，没有打开就要先申请授权。
如果是要把targetSdkVersion设置为小于23，不使用6.0的权限系统的话，要修改tdemovideocall module下的targetSdkVersion才可以。我估计是你修改的module目录不对
@kalufamily

**Comment by guozhuoxing** [comment]
MIUI8          targetSdkVersion 23以下 获取权限貌似不能同时响应两个 后一个框会被前一个挡住  分开申请权限就能解决
