### ISSUE TITLE
心跳无法停止，导致一直发送信令

### ISSUE THREAD

**Issue by arthur20150522** [zhaoyang21cn/ILiveSDK_Android_Demos#24]
对方挂断电话之后，我这边发现没有取消掉心跳线程，还是一直发出，请问是我调用错了还是什么

E/ILVB-CallMgr: processCallEnd->not found id: 840879397
E/ILVB-CallMgr: sendGroupMessage error6011: to user invalid|cmd:{"UserAction":136,"AVRoomID":840879397,"CallType":1,"CallDate":1490172523,"Sender":"363259"}

**Comment by xkazer** [comment]
请确认callsdk使用的是最新版本1.0.14，如果还有此现象，可以发送ILiveSDK日志到xkazerzhang@tencent.com

另: 为保证您的问题能够更快的得到回复，callsdk的问题请移动到[这里](https://github.com/zhaoyang21cn/CallSDK_Android_Demo)提问
