### ISSUE TITLE
IOS CallMgr 有暴露出来，忙碌的接口，安卓没有

### ISSUE THREAD

**Issue by arthur20150522** [zhaoyang21cn/ILiveSDK_Android_Demos#25]
希望CallMgr能够暴露出来一个isBuyOnline()的方法，让用户手动显性的回复忙碌，而不仅仅是通过sdk自己判断。

**Comment by xkazer** [comment]
Android的ILVCallConfig里面，有setAutoBusy配置，可用于设置是否自动拒接来电
