### ISSUE TITLE
下载的demo

### ISSUE THREAD

**Issue by githubjxj** [zhaoyang21cn/ILiveSDK_Android_Demos#29]
下载的demo 用androidstudio 打开 运行 提示Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Failed to create MD5 hash for file 'C:\Users\zosoft\.android\build-cache\355f55ceda8b81ab62473c6606153298e8af8f6e\output\jars\classes.jar'. 怎么解决

**Comment by zhaoyang21cn** [comment]
检查下本地配置项问题
