### ISSUE TITLE
双人视频响应超时的解决方法

### ISSUE THREAD

**Issue by tangpj** [zhaoyang21cn/ILiveSDK_Android_Demos#3]
我在使用Demo的时候，发现双人视频这个功能不能正常运行，返回的错误代码是9005响应超时。经过我的研究发现是tdemovideocall没有使用demo中的全局Application的原因。
我的解决方法是：
1. 在tdemovideocall的build文件中增加 compile project(':suixinbo')；
2. 在tdemovideocall的AndroidManifest.xml文件的application标签下添加：android:name="com.tencent.qcloud.suixinbo.QavsdkApplication"引入全局的application。
这样就解决了双人视频的时候没有显示回调对话框的问题了。
遇到同样问题的用户可以参考我的解决方法

**Comment by guozhuoxing** [comment]
自问自答  吊吊的 👍

**Comment by guozhuoxing** [comment]
为什么要依赖随心播？ 这样包大很多

**Comment by tangpj** [comment]
@guozhuoxing 可以不依赖随心播的，你可以参照随心播里面的QavsdkApplication自己实现一个Applictaion类。出现这个问题的原因是双人视频的时候没有初始化消息回调相关的类，无法发确认接受视频。所以会出现响应超时的错误。因为在demo中的随心播Module里面看到有个全局的Application，所以就偷懒直接依赖随心播了。
