### ISSUE TITLE
直播视频倒立问题

### ISSUE THREAD

**Issue by yjjhkyq** [zhaoyang21cn/ILiveSDK_Android_Demos#32]
主播端视频正立显示，但是网页端查看直播视频倒立显示问题 
操作步骤：
（1）Android平板（不是手机）横屏立起来放置
（2）开直播 （APP接收到后台发送的命令后自动开启直播，不需要人去触碰平板电脑）
（3）通过网页查看直播视频。
期望结果：网页端能够正立显示视频。
实际结果：网页端视频有时候是倒立显示，并且去动一下平板，视频又正常了。

请问下这个问题有没有什么好的解决方法？

**Comment by fxjiao** [comment]
你好 请问你用横屏拍的直播视频在手机上竖屏收看方向正常吗？

**Comment by fxjiao** [comment]
yjjhkyq  你的问题是不是设置了开启自动旋转？
