### ISSUE TITLE
自己的画面是倒立的，而对方看着是正立的

### ISSUE THREAD

**Issue by guangzq** [zhaoyang21cn/ILiveSDK_Android_Demos#37]
版本：直播业务功能
           compile 'com.tencent.livesdk:livesdk:1.1.1'
           核心功能
           compile 'com.tencent.ilivesdk:ilivesdk:1.4.2'

问题：自己看自己的画面是倒立的（与实际画面相差180度），而在对方看来，自己的画面是正立的
期望：无论从哪一方看来，画面都是正的

**Comment by zhaoyang21cn** [comment]
升级已修改
