### ISSUE TITLE
直播过程中暂停不了

### ISSUE THREAD

**Issue by githappygo** [zhaoyang21cn/ILiveSDK_Android_Demos#56]
直播过程中，网络切换的时候比如切到移动网络，想要暂停当前直播，发现AVRootView的onPause ，onResume方法无效

**Comment by xkazer** [comment]
这个只对观众有效，直播本身是支持后台上行的，如果暂停直播，可以关闭摄像头，麦克风，恢复时再打开

**Comment by githappygo** [comment]
@xkazer 我是指的是客户端接收方暂停直播画面，不是主播暂停，就是客户端画面如何暂停然后恢复，就像是断网然后恢复

**Comment by xkazer** [comment]
客户端要暂停画面，可以先取消视频请求，恢复时，再去请求视频画面
