### ISSUE TITLE
70016错误

### ISSUE THREAD

**Issue by zj2050** [zhaoyang21cn/ILiveSDK_Android_Demos#62]
Authentication Server Failed, Please Try Again

**Comment by zj2050** [comment]
用托管模式申请的sdkappid 和 type 也不正确， 也是在 iLiveLogin  的时候错误，错误码：70009
请指教

**Comment by xkazer** [comment]
70009 | 用业务公钥验证sig失败，请确认生成的 usersig 使用的私钥和 sdkappid 是否对应
70016 | 拉取到的公钥长度为0，请确认是否已经上传了公钥，如果是重新上传的公钥需要十分钟之后尝试

从错误码看，两次使用的是都是独立模式

**Comment by zj2050** [comment]
@xkazer 你好，请问7009 生成usersig使用的私钥 和 sddappid是否对应， 私钥在哪儿生成， app中如何应用， 如何和sdkappid 对应？  谢谢，确实不懂

**Comment by zj2050** [comment]
@xkazer 而且托管模式登录，没有返回的token， 没有token创建不了房间啊？ 谢谢

**Comment by xkazer** [comment]
[账号集成说明](https://cloud.tencent.com/document/product/269/1507)
token是随心播这个业务服务器的机制，完全可以自己去定制的

**Comment by zj2050** [comment]
@xkazer 你好，请问怎么自己定制？ 我赋值了一个随机数给token， 但提示过期了， 在什么时候赋值合适？？？

**Comment by zj2050** [comment]
@xkazer  我仔细的看了你提供的连接，里面没有任何地方提到token，请指教

**Comment by zj2050** [comment]
@xkazer 你们提供的demo使用独立模式验证的，在demo里面也没有看到使用密钥的啊？ 请提示一下吧，谢谢

**Comment by xkazer** [comment]
token是业务服务器的逻辑，随心播服务器是针对随心播appid计算userSig和下发token的，
你们使用时需要使用自己的业务服务器(可以拿随心播服务器代码来修改)

**Comment by zj2050** [comment]
@xkazer 多谢回复
那我直接用你们的服务器验证，为什么从腾讯云申请的sdkappid，无论是托管模式申请还是独立模式申请，在 iLiveLogin 时都是返回错误呢？ 不是 70009， 就是 70016， 换句话说，我直接用你们的demo代码不做任何变化， 我该从腾讯云怎么申请sdkappid ，替换了demo中就可以用呢？

谢谢
