### ISSUE TITLE
Android没有摄像头，使用USB摄像头，无法识别

### ISSUE THREAD

**Issue by aoyaowang** [zhaoyang21cn/ILiveSDK_Android_Demos#68]
我的Android设备外接的USB摄像头，本身没摄像头，在dev里能看到video0。 有什么办法可以支持这样直播的吗

**Comment by xkazer** [comment]
如果使用系统接口能打开，sdk一般就能打开，如果打不开，只能使用[自定义采集](https://cloud.tencent.com/document/product/268/7645)了
