### ISSUE TITLE
ilivesdk 导入问题

### ISSUE THREAD

**Issue by DovSnier** [zhaoyang21cn/ILiveSDK_Android_Demos#8]
Error:Failed to resolve: com.tencent.ilivesdk:ilivesdk:0.3.6
<a href="openFile:F:/WorkSpace/ILiveSDK_Android_Demos/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

这个是啥问题呢,搞了好久都没有出来
改为0.3.7 版本后为:
Error:A problem occurred configuring project ':app'.
> A problem occurred configuring project ':tdemovideocall'.
   > Could not resolve all dependencies for configuration ':tdemovideocall:_debugPublishCopy'.
      > Could not resolve com.tencent.ilivesdk:ilivesdk:0.3.7.
        Required by:
            ILiveSDK_Android_Demos:tdemovideocall:unspecified
         > Could not resolve com.tencent.ilivesdk:ilivesdk:0.3.7.
            > Could not get resource 'https://jcenter.bintray.com/com/tencent/ilivesdk/ilivesdk/0.3.7/ilivesdk-0.3.7.pom'.
               > Could not GET 'https://jcenter.bintray.com/com/tencent/ilivesdk/ilivesdk/0.3.7/ilivesdk-0.3.7.pom'.
                  > dev-proxy.oa.com

**Comment by xkazer** [comment]
@DovSnier 不好意思，误将代理上传上去了，请更新下代码，已将gradle.properties里的代理删除
