### ISSUE TITLE
关于录制视频的问题

### ISSUE THREAD

**Issue by CuiBow** [zhaoyang21cn/ILiveSDK_Android_Demos#81]
点击录制如何获取该文件的播放地址

**Comment by hzh19216841** [comment]
可以使用腾讯云的事件通知服务：您的服务器注册一个自己的回调URL给腾讯云，腾讯云会在一个新的录制文件生成时通过这个URL通知给您。[参考此处](https://cloud.tencent.com/document/product/454/7917)
