### ISSUE TITLE
请问 sdk 支持对接第三方的美颜吗？

### ISSUE THREAD

**Issue by TuJHgogo** [zhaoyang21cn/ILiveSDK_Android_Demos#85]
如题，请问 sdk 支持对接第三方的美颜吗？

**Comment by xkazer** [comment]
这里[美颜包](https://github.com/zhaoyang21cn/iLiveSDK_Android_Suixinbo/blob/master/doc/ILiveSDK/ilivefiltersdk-README.md)就是接的三方美颜

**Comment by TuJHgogo** [comment]
ok，多谢
