### ISSUE TITLE
网络不好的时候报错，偶现

### ISSUE THREAD

**Issue by sushanqiang** [zhaoyang21cn/ILiveSDK_Android_Demos#86]
# main(1)

java.lang.UnsatisfiedLinkError

No implementation found for int com.tencent.av.internal.AVCollectorCtrl.nativeEnableAVEventStuttersCollector(boolean, com.tencent.av.internal.AVCollectorCtrl$AVEventStuttesCallback) (tried Java_com_tencent_av_internal_AVCollectorCtrl_nativeEnableAVEventStuttersCollector and Java_com_tencent_av_internal_AVCollectorCtrl_nativeEnableAVEventStuttersCollector__ZLcom_tencent_av_internal_AVCollectorCtrl_00024AVEventStuttesCallback_2)

 com.tencent.av.internal.AVCollectorCtrl.nativeEnableAVEventStuttersCollector(Native Method)
 com.tencent.av.internal.AVCollectorCtrl.enableAVEventStuttersCollector(AVCollectorCtrl.java:109)
 com.tencent.ilivesdk.adapter.avsdk_impl.AVSDKCollect.stop(AVSDKCollect.java:71)
 com.tencent.ilivesdk.core.impl.ILVBLogin$6.onSuccess(ILVBLogin.java:250)
 com.tencent.ilivesdk.ILiveFunc.notifySuccess(ILiveFunc.java:43)
 com.tencent.ilivesdk.adapter.avsdk_impl.AVSDKContext.stop(AVSDKContext.java:303)
 com.tencent.ilivesdk.core.impl.ILVBLogin.stopContext(ILVBLogin.java:246)
 com.tencent.ilivesdk.core.impl.ILVBLogin.logoutSDK(ILVBLogin.java:128)
 com.tencent.ilivesdk.core.impl.ILVBLogin.iLiveLogout(ILVBLogin.java:174)
 com.tencent.ilivesdk.core.impl.ILVBLogin.onForceOffline(ILVBLogin.java:39)
 com.tencent.ilivesdk.adapter.imsdk_impl.IMSDKLogin.onForceOffline(IMSDKLogin.java:30)
 com.tencent.imsdk.bu.run(Unknown Source)
 android.os.Handler.handleCallback(Handler.java:761)
 android.os.Handler.dispatchMessage(Handler.java:98)
 android.os.Looper.loop(Looper.java:156)
 android.app.ActivityThread.main(ActivityThread.java:6523)
 java.lang.reflect.Method.invoke(Native Method)
 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by xkazer** [comment]
感谢您的反馈，可以先使用修复版本(1.8.6.1.7)，下一版本(1.8.7)中会修复这个问题
