### ISSUE TITLE
升级到V1.9.4, "IMSDK" 的makecall 返回 10004， "this group type does not enable apply join group"

### ISSUE THREAD

**Issue by zj2050** [zhaoyang21cn/ILiveSDK_Android_Demos#96]
ILVCallOption option = new ILVCallOption(mHostId)
                .callTips("视频")
                .setMemberListener(this)
                .setCallType(ILVCallConstants.CALL_TYPE_VIDEO);

ILVCallManager.getInstance().makeCall(nums.get(0), option, new ILiveCallBack() {
                    @Override
                    public void onSuccess(Object data) {

                    }

                    @Override
                    public void onError(String module, int errCode, String errMsg) {

                    }
                });

以上设置 直接 返回 10004 ， this group type does not enable apply join group

使用1.8.7 的库没有问题

**Comment by xkazer** [comment]
1.9.4 修改默认群组类型为Public，之前默认是AVChatRoom

**Comment by zj2050** [comment]
@xkazer 谢谢
